const stations=[
{title:"Bild 1",prompt:"Wie viele große Ventilatoren sind an der Wand zu sehen?",correct:"3 Ventilatoren",options:["3 Ventilatoren","2 Ventilatoren","4 Ventilatoren","5 Ventilatoren","1 Ventilator","6 Ventilatoren","3 Rohre","3 Fenster"]},
{title:"Bild 2",prompt:"Welche Grundform hat der große Behälter im Mittelpunkt?",correct:"Zylindrisch",options:["Zylindrisch","Würfelförmig","Pyramidenförmig","Kegelförmig","Kugelförmig","Quaderförmig","Ringförmig","Treppenförmig"]},
{title:"Bild 3",prompt:"Welche Farbe hat das Geländer an der Treppe?",correct:"Hellgelb",options:["Hellgelb","Dunkelrot","Moosgrün","Schwarz","Silbergrau","Rostbraun","Blau","Weiß"]},
{title:"Bild 4",prompt:"Welche Farbe hat das große gebogene Rohr?",correct:"Rostorange",options:["Rostorange","Signalrot","Hellblau","Tannengrün","Schwarz","Weiß","Violett","Gelb"]},
{title:"Bild 5",prompt:"Welche Farbe hat der große Träger oben?",correct:"Rot",options:["Rot","Grün","Blau","Gelb","Schwarz","Weiß","Grau","Braun"]},
{title:"Bild 6",prompt:"Was wächst am oder hinter dem Gitter?",correct:"Grüne Pflanzen",options:["Grüne Pflanzen","Rote Blumen","Gelbes Gras","Moosige Steine","Efeu aus Metall","Kleine Bäume","Schilf","Dornenhecken"]},
{title:"Bild 7",prompt:"Aus welchem Material wirkt der hohe Schornstein gebaut?",correct:"Backstein",options:["Backstein","Betonplatten","Glas","Holz","Stahlblech","Naturstein","Kupfer","Kunststoff"]},
{title:"Bild 8",prompt:"Wie viele hohe dunkle Wände stehen deutlich im Vordergrund?",correct:"3 Wände",options:["3 Wände","1 Wand","2 Wände","4 Wände","5 Wände","6 Wände","3 Türme","3 Schornsteine"]},
{title:"Bild 9",prompt:"Welches Wort steht oben rechts auf der Infotafel?",correct:"Wassersystem",options:["Wassersystem","Wasserwerk","Wasserleitung","Wasserbecken","Wasserpark","Wasserweg","Wassertechnik","Wasserstation"]},
{title:"Bild 10",prompt:"Was spiegelt sich besonders im Wasser?",correct:"Brücke und Himmel",options:["Brücke und Himmel","Schornstein und Feuer","Treppe und Tür","Blumen und Schild","Kran und Schild","Fenster und Wand","Rohr und Ventilator","Gitter und Gras"]},
{title:"Bild 11",prompt:"Wie viele kleine helle Öffnungen sieht man oben an der Rückwand?",correct:"3 Öffnungen",options:["3 Öffnungen","1 Öffnung","2 Öffnungen","4 Öffnungen","5 Öffnungen","6 Öffnungen","3 Türen","3 Lampen"]},
{title:"Bild 12",prompt:"Welche zwei Farben fallen an den Gittern besonders auf?",correct:"Weiß und Rot",options:["Weiß und Rot","Grün und Blau","Gelb und Schwarz","Braun und Grau","Orange und Blau","Weiß und Grün","Rot und Gelb","Schwarz und Silber"]},
{title:"Bild 13",prompt:"Welche Form haben die beiden großen Türen in der Mitte?",correct:"Rechteckig",options:["Rechteckig","Rund","Dreieckig","Oval","Sechseckig","Bogenförmig","Zickzackförmig","Spiralförmig"]},
{title:"Bild 14",prompt:"Wie viele senkrechte graue Rohre stehen links vor der Backsteinwand?",correct:"2 Rohre",options:["2 Rohre","1 Rohr","3 Rohre","4 Rohre","5 Rohre","6 Rohre","2 Schornsteine","2 Türen"]},
{title:"Bild 15",prompt:"Welche Farbe haben die Blüten auf dem Schild?",correct:"Violett",options:["Violett","Rot","Gelb","Weiß","Blau","Orange","Grün","Schwarz"]}
];
const storageKey="landschaftspark-rallye-v2";const views=document.querySelectorAll(".view");const stationGrid=document.querySelector("#stationGrid");const answerGrid=document.querySelector("#answerGrid");const feedback=document.querySelector("#feedback");const headerScore=document.querySelector("#headerScore");const totalScore=document.querySelector("#totalScore");const finishedCount=document.querySelector("#finishedCount");const progressFill=document.querySelector("#progressFill");const progressList=document.querySelector("#progressList");let state=JSON.parse(localStorage.getItem(storageKey)||"{}");let currentIndex=0;
function save(){localStorage.setItem(storageKey,JSON.stringify(state))}function pos(index){const col=index%3;const row=Math.floor(index/3);return (col*50)+"% "+(row*25)+"%"}function showView(id){views.forEach(view=>view.classList.toggle("is-active",view.id===id));if(id==="rallyView")renderStations();if(id==="progressView")renderProgress()}function resultFor(index){return state[String(index+1)]||null}function total(){return Object.values(state).reduce((sum,item)=>sum+(item.points||0),0)}function attemptsFor(index){return state["attempts-"+(index+1)]||0}function setAttempts(index,value){state["attempts-"+(index+1)]=value;save()}function updateScore(){headerScore.textContent=total()}
function renderStations(){updateScore();stationGrid.innerHTML="";stations.forEach((station,index)=>{const result=resultFor(index);const button=document.createElement("button");button.type="button";button.className="station-btn"+(result?" is-complete":"");button.style.setProperty("--pos",pos(index));button.dataset.points=result?result.points:0;button.innerHTML="<strong>"+station.title+"</strong><small>"+(result?"abgeschlossen":"offen")+"</small>";button.addEventListener("click",()=>{if(result){showView("progressView");return}openQuestion(index)});stationGrid.appendChild(button)})}
function openQuestion(index){currentIndex=index;const station=stations[index];document.querySelector("#questionNumber").textContent=station.title;document.querySelector("#questionText").textContent=station.prompt;document.querySelector("#questionImage").style.setProperty("--pos",pos(index));feedback.textContent="";renderAnswers();showView("questionView")}
function renderAnswers(){const station=stations[currentIndex];const attempts=attemptsFor(currentIndex);document.querySelector("#attemptInfo").textContent=attempts===0?"3 Punkte möglich":"1 Punkt möglich";answerGrid.innerHTML="";station.options.forEach(option=>{const button=document.createElement("button");button.type="button";button.className="answer-btn";button.textContent=option;button.addEventListener("click",()=>answer(option,button));answerGrid.appendChild(button)})}
function finishQuestion(points,chosen){const id=String(currentIndex+1);state[id]={points:points,chosen:chosen,correct:stations[currentIndex].correct,title:stations[currentIndex].title};delete state["attempts-"+id];save();updateScore();answerGrid.querySelectorAll("button").forEach(btn=>btn.disabled=true);window.setTimeout(()=>showView("progressView"),900)}
function answer(option,button){const station=stations[currentIndex];const attempts=attemptsFor(currentIndex);if(option===station.correct){button.classList.add("is-right");feedback.textContent=attempts===0?"Richtig. Das gibt 3 Punkte.":"Richtig. Das gibt 1 Punkt.";finishQuestion(attempts===0?3:1,option);return}button.classList.add("is-wrong");button.disabled=true;if(attempts===0){setAttempts(currentIndex,1);feedback.textContent="Nicht ganz. Du hast noch einen Versuch für 1 Punkt.";document.querySelector("#attemptInfo").textContent="1 Punkt möglich";return}feedback.textContent="Leider falsch. Die Frage ist abgeschlossen.";finishQuestion(0,option)}
function renderProgress(){updateScore();const completed=stations.filter((_,index)=>resultFor(index)).length;totalScore.textContent=total();finishedCount.textContent=completed+" von "+stations.length+" Fragen abgeschlossen";progressFill.style.width=((completed/stations.length)*100)+"%";progressList.innerHTML="";stations.forEach((station,index)=>{const result=resultFor(index);const points=result?result.points:0;const item=document.createElement("article");item.className="progress-item";item.innerHTML="<div><strong>"+station.title+"</strong><small>"+(result?"Antwort: "+result.chosen:"Noch offen")+"</small></div><span class='points "+(points===3?"good":points===1?"mid":"")+"'>"+points+" P</span>";progressList.appendChild(item)})}
document.querySelector("#startBtn").addEventListener("click",()=>showView("rallyView"));document.querySelector("#progressBtn").addEventListener("click",()=>showView("progressView"));document.querySelectorAll("[data-view]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.view)));document.querySelector("#resetBtn").addEventListener("click",()=>{state={};save();renderProgress();renderStations()});renderStations();renderProgress();showView("homeView");
